Controllers/AdminPanelController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebLearningMVCEF.Controllers
{
    public class AdminPanelController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ManageAccountsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Collections.Generic;
using WebLearningMVCEF.Data;
using WebLearningMVCEF.Models;
using WebLearningMVCEF.Models.ViewModels;
using System.Threading.Tasks;

namespace WebLearningMVCEF.Controllers
{
    public class ManageAccountsController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ManageAccountsController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<User> usersList = _db.Users;

            foreach (User user in usersList)
            {
                user.RoleType = _db.RolesTypes.FirstOrDefault(role => role.Id == user.RoleTypeId);
            }

            return View(usersList);
        }

        public IActionResult NewUser()
        {
            //IEnumerable<SelectListItem> TypeDropDown = _db.RolesTypes.Select(i => new SelectListItem
            //{
            //    Text = i.Name,
            //    Value = i.Id.ToString()
            //});

            //ViewBag.TypeDropDown = TypeDropDown;

            UserVM userVM = new()
            {
                User = new User(),
                RolesTypesDropDown = _db.RolesTypes.Select(item => new SelectListItem
                {
                    Text = item.Name,
                    Value = item.Id.ToString()
                })
            };

            return View(userVM);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult NewUser(UserVM userVM)
        {
            // This is server side validation, but it's to easy task to do it on server side, better is Client Side Validation implemented directly in View
            if (ModelState.IsValid)
            {
                _db.Users.Add(userVM.User);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userVM);
        }

        public IActionResult DeleteUser(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            User obj = _db.Users.Find(id);

            if (obj == null) {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteUserPost(int? id)
        {
            User obj = _db.Users.Find(id);
            if (obj == null) 
            { 
                return NotFound(); 
            }

            _db.Users.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult UpdateUser(int? id)
        {
            //User obj = _db.Users.Find(id);

            //if (obj == null)
            //{
            //    return NotFound();
            //}

            //IEnumerable<SelectListItem> TypeDropDown = _db.RolesTypes.Select(i => new SelectListItem
            //{
            //    Text = i.Name,
            //    Value = i.Id.ToString()
            //});

            //ViewBag.TypeDropDown = TypeDropDown;

            UserVM userVM = new UserVM()
            {
                User = new User(),
                RolesTypesDropDown = _db.RolesTypes.Select(item => new SelectListItem
                {
                    Text = item.Name,
                    Value = item.Id.ToString()
                })
            };

            if (id == null || id == 0)
            {
                return NotFound();
            }

            userVM.User = _db.Users.Find(id);

            if (userVM.User == null)
            {
                return NotFound();
            }

            return View(userVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateUser(UserVM userVM)
        {

            //userVM.User.RoleType = _db.RolesTypes.Find(2);

            if (ModelState.IsValid)
            {
                _db.Users.Update(userVM.User);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userVM);
        }
    }
}

Controllers/ManageRoleTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebLearningMVCEF.Data;
using WebLearningMVCEF.Models;

namespace WebLearningMVCEF.Controllers
{
    public class ManageRoleTypesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ManageRoleTypesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: RoleTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.RolesTypes.ToListAsync());
        }

        // GET: RoleTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roleType = await _context.RolesTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (roleType == null)
            {
                return NotFound();
            }

            return View(roleType);
        }

        // GET: RoleTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: RoleTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,AccessLevel")] RoleType roleType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(roleType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(roleType);
        }

        // GET: RoleTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roleType = await _context.RolesTypes.FindAsync(id);
            if (roleType == null)
            {
                return NotFound();
            }
            return View(roleType);
        }

        // POST: RoleTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,AccessLevel")] RoleType roleType)
        {
            if (id != roleType.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(roleType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleTypeExists(roleType.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(roleType);
        }

        // GET: RoleTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roleType = await _context.RolesTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (roleType == null)
            {
                return NotFound();
            }

            return View(roleType);
        }

        // POST: RoleTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var roleType = await _context.RolesTypes.FindAsync(id);
            _context.RolesTypes.Remove(roleType);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoleTypeExists(int id)
        {
            return _context.RolesTypes.Any(e => e.Id == id);
        }
    }
}

Views/AdminPanel/AddUser.cshtml
@model WebLearningMVCEF.Models.User

@{
    ViewData["Title"] = "AddUser";
}

<h1>AddUser</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddUser">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NickName" class="control-label"></label>
                <input asp-for="NickName" class="form-control" />
                <span asp-validation-for="NickName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Login" class="control-label"></label>
                <input asp-for="Login" class="form-control" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoleTypeId" class="control-label"></label>
                <select asp-for="RoleTypeId" class ="form-control" asp-items="ViewBag.RoleTypeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondName" class="control-label"></label>
                <input asp-for="SecondName" class="form-control" />
                <span asp-validation-for="SecondName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreditCard" class="control-label"></label>
                <input asp-for="CreditCard" class="form-control" />
                <span asp-validation-for="CreditCard" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/AdminPanel/Index.cshtml
<table class="flex-column flex-lg-wrap">
	<tbody>
		<td>
			<a class="btn btn-outline-primary" asp-controller="ManageAccounts" asp-action="Index">Manage Accounts</a>
		</td>
		<td>
			<a class="btn btn-outline-primary" asp-controller="ManageRoleTypes" asp-action="Index">Manage Role Types</a>
		</td>
		<td>
			<a class="btn btn-outline-primary" asp-controller="ManageGames" asp-action="Index">Manage Accounts</a>
		</td>
		<td>
			<a class="btn btn-outline-primary" asp-controller="ManagePegi" asp-action="Index">Manage Accounts</a>
		</td>
		<td>
			<a class="btn btn-outline-primary" asp-controller="ManageEventsPlaces" asp-action="Index">Manage Accounts</a>
		</td>
		<td>
			<a class="btn btn-outline-primary" asp-controller="ManageGamesTypes" asp-action="Index">Manage Accounts</a>
		</td>
		<td>
			<a class="btn btn-outline-primary" asp-controller="ManagePodiumRanking" asp-action="Index">Manage Accounts</a>
		</td>
		<td>
			<a class="btn btn-outline-primary" asp-controller="ManagePrizeCategory" asp-action="Index">Manage Accounts</a>
		</td>
		<td>
			<a class="btn btn-outline-primary" asp-controller="ManagePrizesTypes" asp-action="Index">Manage Accounts</a>
		</td>
		<td>
			<a class="btn btn-outline-primary" asp-controller="ManageTournaments" asp-action="Index">Manage Accounts</a>
		</td>
		<td>
			<a class="btn btn-outline-primary" asp-controller="ManageTeams" asp-action="Index">Manage Accounts</a>
		</td>
	</tbody>
</table>